// <auto-generated />
using Day_3_EF_Demo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day_3_EF_Demo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day_3_EF_Demo.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "IT"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "HR"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Finance"
                        });
                });

            modelBuilder.Entity("Day_3_EF_Demo.Models.Emplyee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("emplyees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            DepartmentId = 2,
                            Email = "Alice@example.com",
                            Name = "Alice",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 28,
                            DepartmentId = 1,
                            Email = "Bob@example.com",
                            Name = "Bob",
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            DepartmentId = 3,
                            Email = "Charlie@example.com",
                            Name = "Charlie",
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 4,
                            Age = 30,
                            DepartmentId = 1,
                            Email = "Diana@example.com",
                            Name = "Diana",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 5,
                            Age = 24,
                            DepartmentId = 2,
                            Email = "Eve@example.com",
                            Name = "Eve",
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 6,
                            Age = 27,
                            DepartmentId = 3,
                            Email = "Frank@example.com",
                            Name = "Frank",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 7,
                            Age = 29,
                            DepartmentId = 1,
                            Email = "Grace@example.com",
                            Name = "Grace",
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            DepartmentId = 2,
                            Email = "Henry@example.com",
                            Name = "Henry",
                            Salary = 3300m
                        },
                        new
                        {
                            Id = 9,
                            Age = 26,
                            DepartmentId = 3,
                            Email = "Iris@example.com",
                            Name = "Iris",
                            Salary = 3800m
                        },
                        new
                        {
                            Id = 10,
                            Age = 31,
                            DepartmentId = 1,
                            Email = "Jack@example.com",
                            Name = "Jack",
                            Salary = 5200m
                        });
                });

            modelBuilder.Entity("Day_3_EF_Demo.Models.Emplyee", b =>
                {
                    b.HasOne("Day_3_EF_Demo.Models.Department", "Department")
                        .WithMany("Emplyees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Day_3_EF_Demo.Models.Department", b =>
                {
                    b.Navigation("Emplyees");
                });
#pragma warning restore 612, 618
        }
    }
}
