// <auto-generated />
using System;
using MVC_day04_lab.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_day04_lab.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260227034051_addExpireDate")]
    partial class addExpireDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_day04_lab.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("MVC_day04_lab.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 10,
                            Description = "Smart TV",
                            Name = "TV",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 5,
                            Description = "Gaming Laptop",
                            Name = "Laptop",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Count = 50,
                            Description = "Cotton Shirt",
                            Name = "Shirt",
                            Price = 200m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Count = 30,
                            Description = "Jeans Pants",
                            Name = "Pants",
                            Price = 300m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Count = 100,
                            Description = "Whole Wheat Bread",
                            Name = "Bread",
                            Price = 5m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Count = 200,
                            Description = "Low Fat Milk",
                            Name = "Milk",
                            Price = 3m
                        });
                });

            modelBuilder.Entity("MVC_day04_lab.Models.Product", b =>
                {
                    b.HasOne("MVC_day04_lab.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVC_day04_lab.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
